### ISSUE TITLE
Error while installation: uninitialized constant IssueMeetingsHelper (NameError)

### ISSUE THREAD

**Issue by MarkusGrandpre** [ThatCompany/that_meeting#3] opened 2020-09-01 11:50 UTC
Hi Andriy,

we are a University in Germany and we provide Redmine as project management tool to our students and employees. Many of them are used to use the "redmine_meeting" () plugin. But when we like to upgrade to Redmine 4.0.1, we encountered that we cannot use the "redmine_meeting" plugin anymore. So we need to provide your new plugin "that_meeting" asap to our students and employees.

As far as I have learned, there is a problem to include the IssueMeetingsHelper module when I initially try to migrate the plugin data into the Redmine DB:

```
$ sudo rake redmine:plugins:migrate RAILS_ENV=production --trace
(in /usr/share/redmine)
/usr/lib/x86_64-linux-gnu/ruby/2.5.0/etc.so: warning: already initialized constant Etc::SC_AIO_LISTIO_MAX
/usr/lib/x86_64-linux-gnu/ruby/2.5.0/etc.so: warning: already initialized constant Etc::SC_AIO_MAX
/usr/lib/x86_64-linux-gnu/ruby/2.5.0/etc.so: warning: already initialized constant Etc::SC_AIO_PRIO_DELTA_MAX
/usr/lib/x86_64-linux-gnu/ruby/2.5.0/etc.so: warning: already initialized constant Etc::SC_ARG_MAX
/usr/lib/x86_64-linux-gnu/ruby/2.5.0/etc.so: warning: already initialized constant Etc::SC_ATEXIT_MAX
...
/usr/lib/x86_64-linux-gnu/ruby/2.5.0/strscan.so: warning: already initialized constant StringScanner::Version
/usr/lib/x86_64-linux-gnu/ruby/2.5.0/strscan.so: warning: already initialized constant StringScanner::Id
** Invoke redmine:plugins:migrate (first_time)
** Invoke environment (first_time)
** Execute environment
rake aborted!
NameError: uninitialized constant IssueMeetingsHelper
/usr/share/redmine/plugins/that_meeting-master/init.rb:12:in `block in <top (required)>'
/var/lib/gems/2.5.0/gems/activesupport-5.2.4.3/lib/active_support/callbacks.rb:426:in `instance_exec'
/var/lib/gems/2.5.0/gems/activesupport-5.2.4.3/lib/active_support/callbacks.rb:426:in `block in make_lambda'
/var/lib/gems/2.5.0/gems/activesupport-5.2.4.3/lib/active_support/callbacks.rb:198:in `block (2 levels) in halting'
/var/lib/gems/2.5.0/gems/activesupport-5.2.4.3/lib/active_support/callbacks.rb:606:in `block (2 levels) in default_terminator'
/var/lib/gems/2.5.0/gems/activesupport-5.2.4.3/lib/active_support/callbacks.rb:605:in `catch'
/var/lib/gems/2.5.0/gems/activesupport-5.2.4.3/lib/active_support/callbacks.rb:605:in `block in default_terminator'
/var/lib/gems/2.5.0/gems/activesupport-5.2.4.3/lib/active_support/callbacks.rb:199:in `block in halting'
/var/lib/gems/2.5.0/gems/activesupport-5.2.4.3/lib/active_support/callbacks.rb:513:in `block in invoke_before'
/var/lib/gems/2.5.0/gems/activesupport-5.2.4.3/lib/active_support/callbacks.rb:513:in `each'
/var/lib/gems/2.5.0/gems/activesupport-5.2.4.3/lib/active_support/callbacks.rb:513:in `invoke_before'
/var/lib/gems/2.5.0/gems/activesupport-5.2.4.3/lib/active_support/callbacks.rb:131:in `run_callbacks'
/var/lib/gems/2.5.0/gems/activesupport-5.2.4.3/lib/active_support/reloader.rb:89:in `prepare!'
/var/lib/gems/2.5.0/gems/railties-5.2.4.3/lib/rails/application/finisher.rb:63:in `block in <module:Finisher>'
/var/lib/gems/2.5.0/gems/railties-5.2.4.3/lib/rails/initializable.rb:32:in `instance_exec'
/var/lib/gems/2.5.0/gems/railties-5.2.4.3/lib/rails/initializable.rb:32:in `run'
/var/lib/gems/2.5.0/gems/railties-5.2.4.3/lib/rails/initializable.rb:61:in `block in run_initializers'
/usr/lib/ruby/2.5.0/tsort.rb:228:in `block in tsort_each'
/usr/lib/ruby/2.5.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
/usr/lib/ruby/2.5.0/tsort.rb:431:in `each_strongly_connected_component_from'
/usr/lib/ruby/2.5.0/tsort.rb:349:in `block in each_strongly_connected_component'
/usr/lib/ruby/2.5.0/tsort.rb:347:in `each'
/usr/lib/ruby/2.5.0/tsort.rb:347:in `call'
/usr/lib/ruby/2.5.0/tsort.rb:347:in `each_strongly_connected_component'
/usr/lib/ruby/2.5.0/tsort.rb:226:in `tsort_each'
/usr/lib/ruby/2.5.0/tsort.rb:205:in `tsort_each'
/var/lib/gems/2.5.0/gems/railties-5.2.4.3/lib/rails/initializable.rb:60:in `run_initializers'
/var/lib/gems/2.5.0/gems/railties-5.2.4.3/lib/rails/application.rb:361:in `initialize!'
/usr/share/redmine/config/environment.rb:14:in `<top (required)>'
/var/lib/gems/2.5.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/var/lib/gems/2.5.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/var/lib/gems/2.5.0/gems/railties-5.2.4.3/lib/rails/application.rb:337:in `require_environment!'
/var/lib/gems/2.5.0/gems/railties-5.2.4.3/lib/rails/application.rb:520:in `block in run_tasks_blocks'
/usr/lib/ruby/vendor_ruby/rake/task.rb:271:in `block in execute'
/usr/lib/ruby/vendor_ruby/rake/task.rb:271:in `each'
/usr/lib/ruby/vendor_ruby/rake/task.rb:271:in `execute'
/usr/lib/ruby/vendor_ruby/rake/task.rb:213:in `block in invoke_with_call_chain'
/usr/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
/usr/lib/ruby/vendor_ruby/rake/task.rb:193:in `invoke_with_call_chain'
/usr/lib/ruby/vendor_ruby/rake/task.rb:237:in `block in invoke_prerequisites'
/usr/lib/ruby/vendor_ruby/rake/task.rb:235:in `each'
/usr/lib/ruby/vendor_ruby/rake/task.rb:235:in `invoke_prerequisites'
/usr/lib/ruby/vendor_ruby/rake/task.rb:212:in `block in invoke_with_call_chain'
/usr/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
/usr/lib/ruby/vendor_ruby/rake/task.rb:193:in `invoke_with_call_chain'
/usr/lib/ruby/vendor_ruby/rake/task.rb:182:in `invoke'
/usr/lib/ruby/vendor_ruby/rake/application.rb:160:in `invoke_task'
/usr/lib/ruby/vendor_ruby/rake/application.rb:116:in `block (2 levels) in top_level'
/usr/lib/ruby/vendor_ruby/rake/application.rb:116:in `each'
/usr/lib/ruby/vendor_ruby/rake/application.rb:116:in `block in top_level'
/usr/lib/ruby/vendor_ruby/rake/application.rb:125:in `run_with_threads'
/usr/lib/ruby/vendor_ruby/rake/application.rb:110:in `top_level'
/usr/lib/ruby/vendor_ruby/rake/application.rb:83:in `block in run'
/usr/lib/ruby/vendor_ruby/rake/application.rb:186:in `standard_exception_handling'
/usr/lib/ruby/vendor_ruby/rake/application.rb:80:in `run'
/usr/local/bin/rake:27:in `<main>'
Tasks: TOP => redmine:plugins:migrate => environment
```

So the error "NameError: uninitialized constant IssueMeetingsHelper" may maybe point out that only a "require" statement (or somethin similar) is missing in the header of file init.rb? 

Moreover i found in an article about rails helpers, it reads:

"If you want to write good helpers don’t use any instance variables, they may be available in your current view, but they may not be in another view. (..) That will result in an error because of missing variables." 

see <https://www.rubyguides.com/2020/01/rails-helpers/>. Maybe the change in your code would be very simple and I would be eager to test any ideas you provide. Because we need a solution to this problem really quick. Can you help us please?

Thank you in advance and best regards,
Markus

**Comment by s-andy** [comment] 2021-06-01 10:29
This works fine for me under Redmine 4.0.

I believe, the issue is not in the plugin, but, e.g., in environment. Do you still experience it?

**Comment by s-andy** [comment] 2021-09-24 10:22
Closing this bug report as it does not seem to be actual any more.

**Closed by s-andy** 2021-09-24 10:22 UTC
Labels: invalid
